# Generated by Django 4.1.1 on 2022-09-14 21:25

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost_alter_post_created_at_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 0, 25, 25, 697071)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e312c8a2-2da2-47e9-b29e-90ccaaaf611a'), primary_key=True, serialize=False),
        ),
    ]
